---
- name: Stop and shutdown gateway
  hosts: gateway
  become: true
  roles:
    - shutdown

- name: Stop and shutdown workers
  hosts: workers
  become: true
  roles:
    - shutdown

- name: Stop and shutdown masters
  hosts: masters
  become: true
  roles:
    - shutdown

- name: Optionally shutdown bastion
  hosts: bastion
  become: true
  roles:
    - shutdown
