spark.master                             yarn
spark.submit.deployMode                  client
spark.eventLog.enabled                   true
spark.eventLog.dir                       hdfs:///spark-logs
spark.history.fs.logDirectory            hdfs:///spark-logs
spark.driver.memory                      512m
spark.executor.memory                    512m
spark.executor.cores                     1
spark.sql.warehouse.dir                  hdfs:///user/hive/warehouse
spark.hadoop.hive.metastore.uris         thrift://localhost:9083
spark.yarn.appMasterEnv.JAVA_HOME        /usr/lib/jvm/java-11-openjdk-amd64
spark.executorEnv.JAVA_HOME              /usr/lib/jvm/java-11-openjdk-amd64
spark.yarn.appMasterEnv.HADOOP_CONF_DIR  /opt/hadoop/etc/hadoop
spark.executorEnv.HADOOP_CONF_DIR        /opt/hadoop/etc/hadoop
