student_ssh_keys:
  elom.edah:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrGVv/7p/kn1vDTPYUNT4C8Kno5SCfV+59KegmD2ZyV
  nicolas.marie:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQYFYPB8E11yUvbMqNQ/6yqiV8DsUJYiYPi2lPSXCFk
