student_ssh_keys:
  denance.guillaume:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMmEG2Nvq2Par0scHYq1Wpx3Srtp7rW87S5BoNas99+e
  elom.edah:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrGVv/7p/kn1vDTPYUNT4C8Kno5SCfV+59KegmD2ZyV
  noyon.patrick:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEHpjfNrj59OJtWcfPEr/dXONFtvjheBl1BUUs1If9cZ
  nicolas.marie:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQYFYPB8E11yUvbMqNQ/6yqiV8DsUJYiYPi2lPSXCFk
  toma.chang:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPDJCp8BQgkoMRvOJVGU4DbxUOiQ/ovpIbWwJHZJwWIS
  nicolas.soubigou:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJU1f4aOL/j9Q/3HcnXYaWwqeFiNpwwpBaZ2iKdAvvp7
  toma.chang:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPDJCp8BQgkoMRvOJVGU4DbxUOiQ/ovpIbWwJHZJwWIS
  vitse.kevin:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMYix9VszWWHKHRfqKHTJB17pGhvvfALt2CF02eVIcLR
  merimi.elias:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINI0Nkj4iv2zp7sJoOLakLDyfn7EayOYlEzQA4bslcoA
  fatma.itchir
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILf0hhC85qMscksBqLQYCK2BSUnY8v2xQJz2ztqxVuBj
